package com.fvgprinc.tools.utilities.swing.ui;

import com.fvgprinc.tools.utilities.swing.interfaces.DialogCapable;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryzen9-Gaming
 */
public class JdlgSimpleData extends javax.swing.JDialog implements DialogCapable {

    private int result;
    //private String dataStr;

    /**
     * Creates new form JdlgConfirmDelete
     *
     * @param parent
     * @param title
     * @param message
     * @param modal
     */
    public JdlgSimpleData(java.awt.Frame parent, String title, String message, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle(title);
        lbMessage.setText(message);
        initMyComponents();
        this.setLocationRelativeTo(parent);
        this.setResizable(false);
    }

    private void initMyComponents() {
        btnCancel.addActionListener(e -> cancelDialog());
        btnOk.addActionListener(e -> okDialog());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbMessage = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOk.setText("Ok");

        btnCancel.setText("Cancel");

        lbMessage.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnOk)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessage)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @Override
    public void showDialog() {
        this.setVisible(true);
    }

    @Override
    public void okDialog() {
        result = JOptionPane.OK_OPTION;
        dispose();
    }

    @Override
    public void cancelDialog() {
        result = JOptionPane.CANCEL_OPTION;
        dispose();
    }

    @Override
    public int getResult() {
        return this.result;
    }

    public void setData(String strData) {
        tfData.setText(strData);
    }

    public String getData() {
        return tfData.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JTextField tfData;
    // End of variables declaration//GEN-END:variables

}
