package com.fvgprinc.tools.utilities.swing.ui;

import com.fvgprinc.tools.utilities.MySwingUtil;
import com.fvgprinc.tools.utilities.swing.model.ColumnGridBe;
import com.fvgprinc.tools.utilities.swing.model.PickListTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author garfi
 */
public class JfrmPickList extends javax.swing.JDialog {

    int result;

    private final ArrayList<ColumnGridBe> lstGridColsBe;

    private String dataPick;

    /**
     * Get the value of dataPick
     *
     * @return the value of dataPick
     */
    public String getDataPick() {
        return dataPick;
    }

    /**
     * Set the value of dataPick
     *
     * @param dataPick new value of dataPick
     */
    public void setDataPick(String dataPick) {
        this.dataPick = dataPick;
    }

    private String columnDataPick;

    /**
     * Get the value of columnDataPick
     *
     * @return the value of columnDataPick
     */
    public String getColumnDataPick() {
        return columnDataPick;
    }

    /**
     * Set the value of columnDataPick
     *
     * @param columnDataPick new value of columnDataPick
     */
    public void setColumnDataPick(String columnDataPick) {
        this.columnDataPick = columnDataPick;
    }

    private String descPick;

    /**
     * Get the value of descPick
     *
     * @return the value of descPick
     */
    public String getDescPick() {
        return descPick;
    }

    /**
     * Set the value of descPick
     *
     * @param descPick new value of descPick
     */
    public void setDescPick(String descPick) {
        this.descPick = descPick;
    }

    private String columnDescPick;

    /**
     * Get the value of columnDescPick
     *
     * @return the value of columnDescPick
     */
    public String getColumnDescPick() {
        return columnDescPick;
    }

    /**
     * Set the value of columnDescPick
     *
     * @param columnDescPick new value of columnDescPick
     */
    public void setColumnDescPick(String columnDescPick) {
        this.columnDescPick = columnDescPick;
    }

    public void setDataModel(PickListTableModel pickListTableModel) {
        jTblData.setModel(pickListTableModel);
    }

    public void setColumnTableDataWidth(int col, int width) {
        this.jTblData.getColumnModel().getColumn(col).setPreferredWidth(width);
    }

    public JTable getjTblData() {
        return jTblData;
    }

    public JfrmPickList(java.awt.Frame parent, boolean modal, String title, ArrayList<ColumnGridBe> lstCols) {
        super(parent, modal);
        initComponents();
        this.setTitle(title);
        this.setLocationRelativeTo(parent);
        this.lstGridColsBe = lstCols;
        ListSelectionModel selectionModel = jTblData.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPnlParameters = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtnSearch = new javax.swing.JButton();
        jTxtFldToSearch = new javax.swing.JTextField();
        jPnlGrid = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblData = new javax.swing.JTable();
        jPnlButtons = new javax.swing.JPanel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPnlParameters.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Buscar");

        jBtnSearch.setText("Buscar");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jTxtFldToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldToSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlParametersLayout = new javax.swing.GroupLayout(jPnlParameters);
        jPnlParameters.setLayout(jPnlParametersLayout);
        jPnlParametersLayout.setHorizontalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParametersLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jTxtFldToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlParametersLayout.setVerticalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParametersLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBtnSearch))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPnlGrid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblData);

        javax.swing.GroupLayout jPnlGridLayout = new javax.swing.GroupLayout(jPnlGrid);
        jPnlGrid.setLayout(jPnlGridLayout);
        jPnlGridLayout.setHorizontalGroup(
            jPnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        jPnlGridLayout.setVerticalGroup(
            jPnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlGridLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPnlButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jBtnCancel.setText("Cancel");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlButtonsLayout = new javax.swing.GroupLayout(jPnlButtons);
        jPnlButtons.setLayout(jPnlButtonsLayout);
        jPnlButtonsLayout.setHorizontalGroup(
            jPnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlButtonsLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlButtonsLayout.setVerticalGroup(
            jPnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlButtonsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnlGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPnlParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.result = JOptionPane.CANCEL_OPTION;
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private int getColumnIndexByName(String columnName) {
        int res = -1;
        boolean found = false;

        for (int i = 0; i < lstGridColsBe.size() && !found; i++) {
            ColumnGridBe gridBe = (ColumnGridBe) lstGridColsBe.get(i);
            if (gridBe.getNomFisico().equalsIgnoreCase(columnName)) {
                res = i;
                found = true;
            }
        }
        return res;
    }

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        selectRowTableValue();
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void selectRowTableValue() {
        this.result = JOptionPane.OK_OPTION;
        if (jTblData.getSelectedRow() != -1) {
            int curRow = jTblData.getSelectedRow();

            int dataCol = getColumnIndexByName(this.columnDataPick);
            System.out.println("dataCol " + Integer.toString(dataCol));
            dataPick = (String) jTblData.getValueAt(curRow, dataCol);
            System.out.println("dataPick " + dataPick);
            int descCol = getColumnIndexByName(this.columnDescPick);
            System.out.println("descCol " + Integer.toString(descCol));
            descPick = (String) jTblData.getValueAt(curRow, descCol);
            System.out.println("descPick " + descPick);
            this.dispose();
        } else {
            MySwingUtil.mostrarMensaje("No seleccionó ningún registro", MySwingUtil.TD_ERROR, "Edición");
        }

    }

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        TableRowSorter<AbstractTableModel> sorter = (TableRowSorter<AbstractTableModel>) jTblData.getRowSorter();
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + jTxtFldToSearch.getText()));
        jTblData.updateUI();
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jTxtFldToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldToSearchActionPerformed
        jBtnSearchActionPerformed(evt);
    }//GEN-LAST:event_jTxtFldToSearchActionPerformed

    private void jTblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDataMouseClicked
        if (evt.getClickCount() == 2) {
            selectRowTableValue();
        }
    }//GEN-LAST:event_jTblDataMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlButtons;
    private javax.swing.JPanel jPnlGrid;
    private javax.swing.JPanel jPnlParameters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblData;
    private javax.swing.JTextField jTxtFldToSearch;
    // End of variables declaration//GEN-END:variables

// Método para obtener el resultado del diálogo
    public int showDialog() {
        setVisible(true);
        return result;
    }

}
